name: flood
description: A data-generator for databases using Aqueduct
version: 0.1.1
homepage: https://github.com/CurC/flood
author: Curtis Chin Jen Sem <csochinjensem@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  aqueduct: ^3.1.0+1
  faker: ^1.0.0

dev_dependencies:
  pedantic: ^1.4.0
  test: ^1.0.0
  aqueduct_test: ^1.0.0
